name: Generate

on:
  push:
    tags:
      - '*'

jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.8.10"
          cache: 'pip'
      - name: Run
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: pip --disable-pip-version-check install -r requirements.txt && python main.py
      - name: Release
        uses: fnkr/github-action-ghr@v1
        env:
          GHR_PATH: json/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}