name: auto Bump version
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.ACTION_TOKEN }}